/**
 * Valid CSS custom property names from brand-variables.scss.
 * No hex values here — colors resolve at runtime via var(--name).
 */
export type TextColor =
  | 'primary-color-1'
  | 'primary-color-2'
  | 'primary-color-3'
  | 'primary-color-4'
  | 'primary-color-5'
  | 'primary-color-6'
  | 'semantic-alert-bg'
  | 'secondary-color-1-dark'
  | 'secondary-color-1-base'
  | 'secondary-color-1-light'
  | 'secondary-color-2-dark'
  | 'secondary-color-2-base'
  | 'secondary-color-2-light'
  | 'secondary-color-3-dark'
  | 'secondary-color-3-base'
  | 'secondary-color-3-light'
  | 'secondary-color-4-dark'
  | 'secondary-color-4-base'
  | 'secondary-color-4-light'
  | 'secondary-color-5-dark'
  | 'secondary-color-5-base'
  | 'secondary-color-5-light'
  | 'secondary-color-6-dark'
  | 'secondary-color-6-base'
  | 'secondary-color-6-light'
  | 'grey-1000'
  | 'grey-900'
  | 'grey-800'
  | 'grey-700'
  | 'grey-600'
  | 'grey-500'
  | 'grey-400'
  | 'grey-300'
  | 'grey-200'
  | 'grey-100'
  | 'white-alpha-100'
  | 'white-alpha-90'
  | 'white-alpha-80'
  | 'white-alpha-70'
  | 'white-alpha-60'
  | 'white-alpha-50'
  | 'white-alpha-40'
  | 'white-alpha-30'
  | 'white-alpha-20'
  | 'white-alpha-10';
